SELECT ri1.FOOD_TYPE, ri1.REST_ID, ri1.REST_NAME, ri1.FAVORITES
FROM REST_INFO AS ri1
    JOIN (
        SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
        FROM REST_INFO
        GROUP BY FOOD_TYPE
    ) AS ri2 ON ri1.FOOD_TYPE = ri2.FOOD_TYPE AND ri1.FAVORITES = ri2.MAX_FAVORITES
ORDER BY ri1.FOOD_TYPE DESC;
