SELECT ii.INGREDIENT_TYPE AS INGREDIENT_TYPE, SUM(fh.TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO AS ii
    JOIN FIRST_HALF AS fh ON ii.FLAVOR = fh.FLAVOR
GROUP BY ii.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;
