WITH MOST_VIEWED_USED_GOODS_BOARD AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT CONCAT('/home/grep/src/', b.BOARD_ID, '/', f.FILE_ID, f.FILE_NAME, f.FILE_EXT) AS FILE_PATH
FROM MOST_VIEWED_USED_GOODS_BOARD AS b
    JOIN USED_GOODS_FILE AS f ON b.BOARD_ID = f.BOARD_ID
ORDER BY f.FILE_ID DESC;
