WITH FRONTEND AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
), PYTHON AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
), C_SHARP AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
), GRADE AS (
    SELECT
        ID,
        CASE
            WHEN SKILL_CODE & FRONTEND.CODE AND SKILL_CODE & PYTHON.CODE THEN 'A'
            WHEN SKILL_CODE & C_SHARP.CODE THEN 'B'
            WHEN SKILL_CODE & FRONTEND.CODE THEN 'C'
        END AS GRADE
    FROM DEVELOPERS, FRONTEND, PYTHON, C_SHARP
)

SELECT g.GRADE, d.ID, d.EMAIL
FROM DEVELOPERS AS d
    JOIN GRADE AS g ON d.ID = g.ID
WHERE g.GRADE IS NOT NULL
ORDER BY g.GRADE, d.ID;
