SELECT
    fi.ID AS ID,
    fni.FISH_NAME AS FISH_NAME,
    fi.LENGTH AS LENGTH
FROM (
    SELECT
        ID,
        FISH_TYPE,
        LENGTH,
        MAX(LENGTH) OVER(PARTITION BY FISH_TYPE) AS MAX_LENGTH
    FROM FISH_INFO
) AS fi JOIN FISH_NAME_INFO AS fni ON fi.FISH_TYPE = fni.FISH_TYPE
WHERE fi.LENGTH = fi.MAX_LENGTH
ORDER BY fi.ID;
