SELECT ai.ANIMAL_ID, ai.ANIMAL_TYPE, ai.NAME
FROM ANIMAL_INS AS ai
    JOIN ANIMAL_OUTS AS ao ON ai.ANIMAL_ID = ao.ANIMAL_ID
WHERE SUBSTRING_INDEX(ai.SEX_UPON_INTAKE, ' ', 1) = 'Intact' AND
      (SUBSTRING_INDEX(ao.SEX_UPON_OUTCOME, ' ', 1) = 'Spayed' OR
      SUBSTRING_INDEX(ao.SEX_UPON_OUTCOME, ' ', 1) = 'Neutered')
ORDER BY ai.ANIMAL_ID ASC;
