SELECT p1.ID, p1.NAME, p1.HOST_ID
FROM PLACES AS p1
    JOIN (
        SELECT HOST_ID, COUNT(*) AS PLACES_COUNT
        FROM PLACES
        GROUP BY HOST_ID
    ) AS p2 ON p1.HOST_ID = p2.HOST_ID AND p2.PLACES_COUNT >= 2
ORDER BY ID ASC;
